MySensei/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI.WebControls;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MySensei.Infrastructure;
using MySensei.Models;

namespace MySensei.Controllers
{
    public class CoursesController : Controller
    {
        private AppIdentityDbContext db = new AppIdentityDbContext();

        private readonly Repository _repository = new Repository();

        // GET: Home
        public ActionResult Index()
        {
            return View(_repository.GetCourses());
        }

        [HttpPost]
        public ActionResult SearchCourses(string SearchString)
        {
            ViewBag.textBoxString = SearchString;
            return View(_repository.SearchCourses(SearchString).ToList());
        }

        public ActionResult SingleCourse(int courseId)
        {
            var course = _repository.GetCourseById(courseId);
            var manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());

            var courseStudentId = course.CourseStudents.ToList();
            if (currentUser == null)
            {
                ViewBag.noLogin = true;
            }
            else
            {
                if (courseStudentId.Any(c => c.Id == currentUser.Id))
                {
                    ViewBag.userIsOnCourse = true;
                }
                else
                {
                    ViewBag.userIsOnCourse = false;
                }

                if (course.CourseTeacherId == currentUser.Id)
                {
                    ViewBag.isTeacher = true;
                }
            }


            return View(course);
        }

        public ActionResult JoinCourse(int courseId)
        {
            var manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            var course = _repository.GetCourseById(courseId);
            
            var currentCourse = db.Courses.FirstOrDefault(c => c.CourseID == courseId);


            if (ModelState.IsValid)
            {
                currentCourse.CourseStudents.Add(currentUser);                
                db.SaveChanges();
                
            }
            return RedirectToAction("SingleCourse", new { courseId = courseId });
        }
        public ActionResult LeaveCourse(int courseId)
        {
            var manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            var course = _repository.GetCourseById(courseId);

            var currentCourse = db.Courses.FirstOrDefault(c => c.CourseID == courseId);


            if (ModelState.IsValid)
            {
                currentCourse.CourseStudents.Remove(currentUser);
                db.SaveChanges();
                
            }
            return RedirectToAction("SingleCourse", new { courseId = courseId });
        }

    }
}

MySensei/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using MySensei.Infrastructure;
using MySensei.Models;

namespace MySensei.Controllers
{
    [Authorize]
    public class LoginController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl = "/Home")
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return View("Error", new string[] { "Access Denied" });
            }

            ViewBag.returnUrl = returnUrl;
            return PartialView("_Login");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginModel details, string returnUrl = "/Home")
        {
            if (string.IsNullOrEmpty(returnUrl))
            {
                returnUrl = "/Home";                
            }


            if (ModelState.IsValid)
            {
                AppUser user = await UserManager.FindAsync(details.UserName, details.Password);
                if (user == null)
                {
                    ModelState.AddModelError("", "Invalid name or password.");
                }
                else
                {
                    ClaimsIdentity ident = await UserManager.CreateIdentityAsync(user,
                    DefaultAuthenticationTypes.ApplicationCookie);
                    AuthManager.SignOut();
                    AuthManager.SignIn(new AuthenticationProperties
                    {
                        IsPersistent = false
                    }, ident);

                    return Redirect(returnUrl);
                }
            }
            ViewBag.returnUrl = returnUrl;
            return Redirect(returnUrl);
        }


        [Authorize]
        public ActionResult Logout()
        {
            AuthManager.SignOut();
            return RedirectToAction("Index", "Home");
        }

        private IAuthenticationManager AuthManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }
    }
}

MySensei/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using MySensei.Infrastructure;
using MySensei.Models;
using MySensei.ViewModels;

namespace MySensei.Controllers
{

    public class ProfileController : Controller
    {
        private readonly Repository _repository = new Repository();
        private AppIdentityDbContext db = new AppIdentityDbContext();

        // GET: Profile
        [Authorize]
        public ActionResult Index()
        {
            //var currentUserId = User.Identity.GetUserId();
            var manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());

            return View(currentUser);

        }

        [AllowAnonymous]
        public ActionResult PublicProfile(string profileId)
        {
            var manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            if (currentUser != null && currentUser.Id == profileId)
            {
                View("Index", currentUser);
            }
            return View(_repository.GetProfileById(profileId));

        }
        [Authorize]
        public async Task<ActionResult> EditProfile()
        {
            var manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            if (currentUser != null)
            {
                return View(currentUser);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> EditProfile(string id, string firstname, string lastname, string description, string username, string email, string password)
        {
            //var currentUserId = User.Identity.GetUserId();
            var manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());

            if (currentUser != null)
            {
                currentUser.FirstName = firstname;
                currentUser.LastName = lastname;
                currentUser.Description = description;
                currentUser.UserName = username;
                currentUser.Email = email;
                IdentityResult validEmail = await manager.UserValidator.ValidateAsync(currentUser);
                if (!validEmail.Succeeded)
                {
                    AddErrorsFromResult(validEmail);
                }

                IdentityResult validPass = null;
                if (password != string.Empty)
                {
                    validPass = await manager.PasswordValidator.ValidateAsync(password);
                    if (validPass.Succeeded)
                    {
                        currentUser.PasswordHash = manager.PasswordHasher.HashPassword(password);
                    }
                    else
                    {
                        AddErrorsFromResult(validPass);
                    }
                }

                if ((validEmail.Succeeded && validPass == null) || (validEmail.Succeeded && password != string.Empty && validPass.Succeeded))
                {
                    IdentityResult result = await manager.UpdateAsync(currentUser);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddErrorsFromResult(result);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "User Not Found");
                }
            }
            return View();
        }

        [Authorize]
        public ActionResult AddCourse(string courseTitle)
        {
            ViewBag.courseTitle = courseTitle;
            var course = new Course();
            course.Tags = new List<Tag>();
            PopulateTagsData(course);
            return View(course);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCourse([Bind(Include = "CourseID,Title,Description,StartDate,EndDate,NumberOfLessons,CourseTeacherId")] Course course, string[] selectedTags)
        {
            if (selectedTags != null)
            {
                course.Tags = new List<Tag>();
                foreach (var tag in selectedTags)
                {
                    var tagToAdd = db.Tags.Find(int.Parse(tag));
                    course.Tags.Add(tagToAdd);
                }
            }

            var manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            course.CourseTeacherId = currentUser.Id;
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }
        [Authorize]
        public ActionResult EditCourse(int? courseId)
        {
            if (courseId == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            //Course course = db.Courses.Find(id);
            Course course = db.Courses
            .Include(c => c.Tags)
            .Where(c => c.CourseID == courseId)
            .Single();
            PopulateTagsData(course);

            if (course == null) { return HttpNotFound(); }

            return View(course);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCourse(int? courseId, string[] selectedTags)
        {
            var courseToUpdate = db.Courses.Include(c => c.CourseTeacher).Include(c => c.Tags).Where(c => c.CourseID == courseId).Single();
            var manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            
            if (TryUpdateModel(courseToUpdate, "", new string[] { "Title", "Description", "StartDate", "EndDate", "NumberOfLessons", "CourseTeacherId" }))
            {
                try
                {
                    UpdateCourseTags(selectedTags, courseToUpdate);
                    db.SaveChanges();
                }
                catch
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }

            // Tags check boxes
            PopulateTagsData(courseToUpdate);

            return View("Index", currentUser);
        }

        // GET: Courses/Delete/5
        public ActionResult DeleteCourse(int? courseId)
        {
            if (courseId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(courseId);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("DeleteCourse")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int courseId)
        {
            Course course = db.Courses
            .Include(c => c.Tags)
            .Where(c => c.CourseID == courseId)
            .Single();
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }


        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }


        private void PopulateTagsData(Course course)
        {
            var allTags = db.Tags;
            var coursesTags = new HashSet<int>(course.Tags.Select(t => t.TagID));
            var viewModel = new List<AssignedTagData>();
            foreach (var tag in allTags)
            {
                viewModel.Add(new AssignedTagData
                {
                    TagID = tag.TagID,
                    TagName = tag.TagName,
                    Assigned = coursesTags.Contains(tag.TagID)
                });
            }
            ViewBag.Tags = viewModel;
        }


        public void UpdateCourseTags(string[] selectedTags, Course courseToUpdate)
        {
            if (selectedTags == null)
            {
                courseToUpdate.Tags = new List<Tag>();
                return;
            }
            var selectedTagsHS = new HashSet<string>(selectedTags);
            var courseTags = new HashSet<int>(courseToUpdate.Tags.Select(t => t.TagID));
            foreach (var tag in db.Tags)
            {
                if (selectedTagsHS.Contains(tag.TagID.ToString()))
                {
                    if (!courseTags.Contains(tag.TagID))
                    {
                        courseToUpdate.Tags.Add(tag);
                    }
                }
                else
                {

MySensei/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MySensei.Infrastructure;
using MySensei.Models;

namespace MySensei.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        public ActionResult Index()
        {
            return PartialView("_Signup");
        }

        [HttpPost]
        public async Task<ActionResult> Index(CreateModel model)
        {
            if (ModelState.IsValid)
            {
                AppUser user = new AppUser { FirstName = model.FirstName, LastName = model.LastName, UserName = model.UserName, Email = model.Email };
                IdentityResult result = await UserManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(model);
        }
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }
    }
}

MySensei/Views/Shared/_Layout.cshtml
@using MySensei.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <title>@ViewBag.Title - MySensei</title>
    <link href="~/Content/styles.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/classie.js"></script>
    <script src="~/Scripts/init.js"></script>
 
</head>
<body>
    <div id="wrapper" class="page-wrap">
        <header>
            <div class="container clearfix">

                <a href="@Url.Action("Index", "Home")">
                    <img class="logo" src="@Url.Content("~/Content/img/logo.png")" />
                </a>
                <nav>
                    <i class="icon-append icon-list"></i>@Html.ActionLink("Oversigt ", "Index", "Courses")
                    @if (User.Identity.IsAuthenticated)
                    {
                        <i class="icon-append icon-user"></i>@Html.ActionLink("Min profil ", "Index", "Profile")
                        <i class="icon-append icon-lock"></i>@Html.ActionLink("Log ud", "Logout", "Account")
                    }
                    else if (!User.Identity.IsAuthenticated)
                    {
                        <i class="icon-append icon-lock"></i><a href="#sidebar">Login</a>
                        <i class="icon-append icon-user"></i><a href="#sidebarSignup">Opret Bruger</a>
                    }
                </nav>
            </div>
        </header><!-- /header -->


        @Html.Partial("_Login", new LoginModel())
        @Html.Partial("_Signup", new CreateModel())
        <div id="main">
            <div id="content">
                
                        @RenderBody()
            </div>
       

            <footer>
                <div class="container center">
                    <p>Cupcake ipsum dolor sit amet lollipop. Macaroon candy cotton candy bear claw macaroon carrot cake pastry icing dessert.</p>
                </div>
            </footer>
            
        </div><!-- #main -->
    </div> <!-- #wrapper -->
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    
    
</body>

</html>








@*<aside class="sidebar" id="sidebar">
    <div class="side-content">
        <a href="#" class="close-menu">&#x02297;</a> <h3>OPRET BRUGER</h3>
        <form action="" class="mform">

            <fieldset>
                <section>
                    <label class="input">
                        <i class="icon-append icon-user"></i>
                        <input type="text" placeholder="Brugernavn">
                        <b class="tooltip tooltip-bottom-right">Kun almindelige tegn og tal</b>
                    </label>
                </section>

                <section>
                    <label class="input">
                        <i class="icon-append icon-envelope-alt"></i>
                        <input type="text" placeholder="Email adresse">
                        <b class="tooltip tooltip-bottom-right">Så vi kan verificere din email</b>
                    </label>
                </section>

                <section>
                    <label class="input">
                        <i class="icon-append icon-lock"></i>
                        <input type="password" placeholder="Password">
                        <b class="tooltip tooltip-bottom-right">Kun almindelige tegn og tal</b>
                    </label>
                </section>

                <section>
                    <label class="input">
                        <i class="icon-append icon-lock"></i>
                        <input type="password" placeholder="Gentag password">
                        <b class="tooltip tooltip-bottom-right">Kun almindelige tegn og tal</b>
                    </label>
                </section>
            </fieldset>

            <fieldset>
                <div class="row">
                    <section class="col half">
                        <label class="input">
                            <input type="text" placeholder="Fornavn">
                        </label>
                    </section>
                    <section class="col half">
                        <label class="input">
                            <input type="text" placeholder="Efternavn">
                        </label>
                    </section>
                </div>

                <section>
                    <label class="select">
                        <select>
                            <option value="0" selected disabled>Køn</option>
                            <option value="1">Mand</option>
                            <option value="2">Kvinde</option>
                        </select>
                        <i></i>
                    </label>
                </section>

                <section>
                    <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Jeg godkender <a href="#">brugerbetingelserne</a></label>

                </section>
            </fieldset>
            <footer>
                <button type="submit" class="button">Opret</button>
            </footer>
        </form>
    </div>
</aside>*@

MySensei/Views/Shared/_Login.cshtml
@model MySensei.Models.LoginModel
<h2>Log In</h2>
@Html.ValidationSummary()
@using (Html.BeginForm("Login", "Login", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <aside class="sidebar" id="sidebar">
        <div class="side-content">
            <a href="#" class="close-menu">&#x02297;</a> <h3>LOGIN</h3>
            <form action="" class="mform">

                <fieldset>
                    <section class="mform">
                        <label class="input">
                            <i class="icon-append icon-user"></i>
                            @Html.TextBoxFor(x => x.UserName, new { @placeholder = "Brugernavn" })
                            <b class="tooltip tooltip-bottom-right">Kun almindelige tegn og tal</b>
                        </label>
                    </section>

                    <section class="mform">
                        <label class="input">
                            <i class="icon-append icon-lock"></i>
                            @Html.PasswordFor(x => x.Password, new { @placeholder = "Password" })
                            <b class="tooltip tooltip-bottom-right">Kun almindelige tegn og tal</b>
                        </label>
                    </section>

                </fieldset>

                <footer>
                    <button type="submit" class="button">Login</button>
                </footer>
            </form>
        </div>
    </aside>



    <button class="button" type="submit">Log In</button>
}

MySensei/Views/Shared/_Signup.cshtml
@model MySensei.Models.CreateModel
<h2>Create User</h2>
@Html.ValidationSummary(false)
@using (Html.BeginForm(Html.BeginForm("Index", "SignUp", FormMethod.Post)))
{
    <aside class="sidebar" id="sidebarSignup">
        <div class="side-content">
            <a href="#" class="close-menu">&#x02297;</a> <h3>OPRET BRUGER</h3>
            <form action="" class="mform">

                <fieldset>
                    <section class="mform">
                        <label class="input">
                            <i class="icon-append icon-user"></i>
                            @Html.TextBoxFor(x => x.UserName, new { @placeholder = "Brugernavn" })
                            <b class="tooltip tooltip-bottom-right">Kun almindelige tegn og tal</b>
                        </label>
                    </section>

                    <section class="mform">
                        <label class="input">
                            <i class="icon-append icon-envelope-alt"></i>
                            @Html.TextBoxFor(x => x.Email, new { @placeholder = "Email" })
                            <b class="tooltip tooltip-bottom-right">Så vi kan verificere din email</b>
                        </label>
                    </section>

                    <section class="mform">
                        <label class="input">
                            <i class="icon-append icon-lock"></i>
                            @Html.PasswordFor(x => x.Password, new { @placeholder = "Password" })
                            <b class="tooltip tooltip-bottom-right">Skal indeholde mindst et stort bogstav og et tal - mindst 6 tegn</b>
                        </label>
                    </section>

                    @*<section class="mform">
                        <label class="input">
                            <i class="icon-append icon-lock"></i>
                            <input type="password" placeholder="Gentag password">
                            <b class="tooltip tooltip-bottom-right">Kun almindelige tegn og tal</b>
                        </label>
                    </section>*@
                </fieldset>
                <div class="clearfix hr"></div>
                <fieldset>
                    <div class="row">
                        <section class="mform">
                            <label class="input">
                                <i class="icon-append icon-user"></i>
                                @Html.TextBoxFor(x => x.FirstName, new { @placeholder = "Fornavn" })
                                <b class="tooltip tooltip-bottom-right">Kun almindelige tegn</b>
                            </label>
                        </section>
                        <section class="mform">
                            <label class="input">
                                <i class="icon-append icon-user"></i>
                                @Html.TextBoxFor(x => x.LastName, new { @placeholder = "Efternavn" })
                                <b class="tooltip tooltip-bottom-right">Kun almindelige tegn</b>
                            </label>
                        </section>
                    </div>

                    @*<section>
                        <label class="select">
                            <select>
                                <option value="0" selected disabled>Køn</option>
                                <option value="1">Mand</option>
                                <option value="2">Kvinde</option>
                            </select>
                            <i></i>
                        </label>
                    </section>*@

                    <section>
                        <label class="checkbox" style="color:#FFF;"><input type="checkbox" name="checkbox"><i></i>Jeg godkender <a href="#">brugerbetingelserne</a></label>
                    
                    <button type="submit" class="button">Opret</button>
                     </section>
                </fieldset>
                
                   
              
            </form>
        </div>
    </aside>
}